import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, extname } from 'node:path'

// The font subset is generated by `npm run fonts` and committed, so the normal
// build needs neither the 7.6MB source nor a network call. The cost of that
// trade is drift: add Chinese copy, forget to regenerate, and those characters
// render as tofu (□) for every visitor whose OS lacks the fallback.
//
// This test closes that gap. It fails the build if any CJK character in source
// content is missing from the committed subset.

const MANIFEST = 'public/fonts/subset-manifest.json'
const SCAN = ['src/content', 'src/i18n', 'src/data', 'src/pages', 'src/components']
const EXT = new Set(['.md', '.ts', '.astro'])

const isCjk = (cp: number) =>
  (cp >= 0x3000 && cp <= 0x303f) ||
  (cp >= 0x3400 && cp <= 0x4dbf) ||
  (cp >= 0x4e00 && cp <= 0x9fff) ||
  (cp >= 0xf900 && cp <= 0xfaff) ||
  (cp >= 0xfe30 && cp <= 0xfe4f) ||
  (cp >= 0xff00 && cp <= 0xffef)

function walk(dir: string): string[] {
  const out: string[] = []
  let entries: string[]
  try {
    entries = readdirSync(dir)
  } catch {
    return out
  }
  for (const entry of entries) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) out.push(...walk(path))
    else if (EXT.has(extname(path))) out.push(path)
  }
  return out
}

function sourceCjk(): Set<number> {
  const found = new Set<number>()
  for (const dir of SCAN) {
    for (const file of walk(dir)) {
      for (const ch of readFileSync(file, 'utf8')) {
        const cp = ch.codePointAt(0)!
        if (isCjk(cp)) found.add(cp)
      }
    }
  }
  return found
}

describe('font subset coverage', () => {
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as {
    codepoints: number[]
    glyphCount: number
  }
  const covered = new Set(manifest.codepoints)

  it('the manifest is non-empty', () => {
    expect(manifest.codepoints.length).toBeGreaterThan(0)
  })

  it('every CJK character in source content is in the committed subset', () => {
    const missing = [...sourceCjk()]
      .filter((cp) => !covered.has(cp))
      .map((cp) => `${String.fromCodePoint(cp)} (U+${cp.toString(16).toUpperCase()})`)

    expect(
      missing,
      `${missing.length} character(s) would render as tofu. Run \`npm run fonts\`:\n  ${missing.join('  ')}`
    ).toEqual([])
  })

  it('her name is covered — the one string that must never fall back', () => {
    for (const ch of '張馬敏妹') {
      expect(covered.has(ch.codePointAt(0)!), `${ch} missing from subset`).toBe(true)
    }
  })
})
